### ISSUE TITLE
How to reproduce the work described in blog "Kubernetes Initializers Deep Dive and Tutorial" based on latest k8s version?

### ISSUE THREAD

**Issue by frankie-yanfeng** [gyliu513/roadmap#7]
Hello Guang Ya Liu,

Thanks for your post.

As a latecomer to kubernetes framework, now I cannot reproduce the work posted into k8s version 1.12+，which the original was based on 1.7.0 alpha.

So, do u have any recommended latest Kubernetes Initializers Tutorial?

Thanks.

**Comment by gyliu513** [comment]
Initializer is not recommended but webhook now, please refer to https://medium.com/ibm-cloud/diving-into-kubernetes-mutatingadmissionwebhook-6ef3c5695f74
